<?php
namespace Desyncr\Wtngrm\Service;

class ConcreteService extends AbstractService {
    public function dispatch() {
        return count($this->jobs);
    }
}

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-12-21 at 19:27:27.
 */
class AbstractServiceTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var AbstractService
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ConcreteService;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Desyncr\Wtngrm\Service\AbstractService::setOptions
     * @todo   Implement testSetOptions().
     */
    public function testSetOptions()
    {

        $options = array(
            'timeout' => 10,
        );

        $this->object->setOptions($options);

        $this->assertEquals($options['timeout'], $this->object->timeout);
    }

    /**
     * @covers Desyncr\Wtngrm\Service\AbstractService::setOptions
     * @todo   Implement testSetOptions().
     */
    public function testSetOptionsNestedArray()
    {

        $options = array(
            'names' => array(
                'John Doe',
                'Jane Doe',
                'Alice',
                'Bob'
            )
        );

        $this->object->setOptions($options);

        $this->assertEquals($options['names'], $this->object->names);
        $this->assertEquals($options['names'][0], $this->object->names[0]);
    }

    /**
     * @covers Desyncr\Wtngrm\Service\AbstractService::setOptions
     * @todo   Implement testSetOptions().
     */
    public function testSetOptionsNestedArrayLevel()
    {

        $options = array(
            'servers' => array(
                'frontend' => array(
                    array('host' => '127.0.0.1', 'port' => 80),
                    array('host' => '127.0.0.1', 'port' => 81)
                ),
                'backend' => array(
                    array('host' => '127.0.0.1', 'port' => 8888)
                )
            )
        );

        $this->object->setOptions($options);

        $this->assertEquals($options['servers']['frontend'], $this->object->servers['frontend']);
        $this->assertEquals($options['servers']['frontend'][1]['port'], $this->object->servers['frontend'][1]['port']);
        $this->assertEquals($options['servers'], $this->object->servers);
    }

    /**
     * @covers Desyncr\Wtngrm\Service\AbstractService::getOption
     * @todo   Implement testGetOptions().
     */
    public function testGetOption()
    {
        $options = array(
            'servers' => array(
                'frontend' => array(
                    array('host' => '127.0.0.1', 'port' => 80)
                )
            )
        );

        $this->object->setOptions($options);

        $this->assertEquals($this->object->getOption('servers'), $options['servers']);
    }

    /**
     * @covers Desyncr\Wtngrm\Service\AbstractService::add
     * @todo   Implement testAdd().
     */
    public function testAdd()
    {
        $key = 'job.service.key';
        $job = array();
        $jobObject = $this->object->add($key, $job);

        $this->assertEquals('Desyncr\Wtngrm\Job\BaseJob', get_class($jobObject));
        $this->assertEquals($jobObject->getId(), $key);
    }

    /**
     * @covers Desyncr\Wtngrm\Service\AbstractService::add
     * @todo   Implement testAdd().
     */
    public function testAddInvalidJob()
    {
        $key = 'job.service.key';
        $job = new \StdClass;
        $this->setExpectedException('Exception');
        $this->object->add($key, $job);
    }

    /**
     * @covers Desyncr\Wtngrm\Service\AbstractService::dispatch
     * @todo   Implement testDispatch().
     */

    public function testDispatch()
    {
        $key = 'job.service.key';
        $job = array();
        $this->object->add($key, $job);

        $this->assertEquals(1, $this->object->dispatch());
    }
}
